import "~/styles/globals.css";
import "highlight.js/styles/github.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`flex justify-center bg-primary pt-8 font-sans prose-headings:text-primary-foreground prose-p:text-primary-foreground prose-code:rounded-md prose-code:bg-[#262625] prose-code:p-[0.25em] prose-code:py-[0.1em] prose-code:text-[#EC5A62] ${inter.variable}`}
      >
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
